import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Particles from "../components/ParticlesBg"; // client component (should have "use client")

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ExoVision - NASA Exoplanet Visualization",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="relative min-h-screen"
        style={{
          fontFamily: "geist-sans",
          fontWeight: "normal",
          backgroundColor: "#111111ff",
          color: "#ffffffff",
          WebkitFontSmoothing: "antialiased",
          MozOsxFontSmoothing: "grayscale",
          overflowX: "hidden",
        }}
      >
        {/* global particles background */}
        <div className="fixed inset-0 -z-10 pointer-events-none">
          <Particles
            particleColors={['#22d3ee', '#000000ff']}
            particleCount={200}
            particleSpread={10}
            speed={0.1}
            particleBaseSize={100}
            moveParticlesOnHover={true}
            alphaParticles={false}
            disableRotation={false}
          />
        </div>

        {children}
      </body>
    </html>
  );
}
